variables:
  IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_DRIVER: overlay

services:
  - docker:20.10-dind

stages:
  - test
  - build
  - deploy

.docker-login:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

.build-docker:
  image: docker:20.10
  script:
    - |
      docker build -t $IMAGE --pull --file ./Dockerfile .
      docker push $IMAGE

.setup-python:
  before_script:
    - pip install poetry
    - poetry env use python
    - python --version ; pip --version; poetry --version  # For debugging
    - poetry install
    - poetry show  # For debugging

.build:
  script:
    - poetry install --only packaging
    - poetry build

.test:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - poetry install --only test
    - poetry run pytest

.deploy:
  after_script:
    - poetry install --only publishing,doc
    - poetry run sphinx-build -b html docs/source public
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token poetry run twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

test-develop:
  image: ${PYTHON}
  stage: test
  except:
    - main
  extends:
    - .setup-python
    - .build
    - .test
  parallel:
    matrix:
      - PYTHON:
        - python:3.8
        - python:3.9
        - python:3.10
        - python:3.11

build-environment:
  stage: build
  only:
    - ci
  extends:
    - .docker-login
    - .build-docker

test-production:
  image: ${PYTHON}
  stage: test
  only:
    - main
  extends:
    - .setup-python
    - .build
    - .test
  parallel:
    matrix:
      - PYTHON:
        - python:3.8
        - python:3.9
        - python:3.10
        - python:3.11

deploy-production:
  image: ${PYTHON}
  stage: deploy
  artifacts:
    paths:
    - public
  only:
    - main
  extends:
    - .setup-python
    - .build
    - .deploy
  parallel:
    matrix:
      - PYTHON:
        - python:3.8
        - python:3.9
        - python:3.10
        - python:3.11
