[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gwasprs"
version = "0.1.0"
authors = [
    { name="Yueh-Hua Tu", email="yuehhua.tu@ailabs.com" },
    { name="Yi-Lun Lee", email="yilun.lee@ailabs.tw" },
]
description = "A GWAS package for supporting federated analysis"
requires-python = ">=3.9"
classifiers = [
   "Programming Language :: Python :: 3",
   "Operating System :: OS Independent",
]

[tool.setuptools.packages]
find = {}
